## **Logistic regression:-**

In [1]:
from sklearn.datasets import load_iris
dataset = load_iris()

In [2]:
import pandas as pd
import numpy as np

In [3]:
df1=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df2=pd.DataFrame(dataset.target,columns=["target"])
df=pd.concat([df1,df2],axis=1)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

create a binary classification dataset:-

In [4]:
df_copy=df[df["target"]!=2]
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

Independent and Dependent feature:-

In [5]:
x=df_copy[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]
y=df_copy["target"]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [8]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [9]:
y_pred=classifier.predict(x_test)

In [10]:
classifier.predict_proba(x_test)

array([[0.96349588, 0.03650412],
       [0.00385311, 0.99614689],
       [0.98329347, 0.01670653],
       [0.00840647, 0.99159353],
       [0.00782444, 0.99217556],
       [0.12199219, 0.87800781],
       [0.98516916, 0.01483084],
       [0.00503538, 0.99496462],
       [0.00404778, 0.99595222],
       [0.02094243, 0.97905757],
       [0.01789731, 0.98210269],
       [0.02225697, 0.97774303],
       [0.00673929, 0.99326071],
       [0.99009868, 0.00990132],
       [0.97535458, 0.02464542],
       [0.96391069, 0.03608931],
       [0.9940572 , 0.0059428 ],
       [0.94661513, 0.05338487],
       [0.98752668, 0.01247332],
       [0.97641253, 0.02358747]])

In [11]:
y_pred

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred))
print("\n ")
print("Accuracy score:- ",accuracy_score(y_test,y_pred))
print("\n ")
print("Classification report\n",classification_report(y_test,y_pred))

Confusion Matrix
 [[10  0]
 [ 0 10]]

 
Accuracy score:-  1.0

 
Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## **Hyperparameter tuning:-**

#### **Gridsearchcv:-**

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [13]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [14]:
parameter={"penalty":("l1","l2","elasticnet",None),"C":[1,10,20]}

##### **spliting of train data to validation data:-**

In [15]:
clf=GridSearchCV(classifier,param_grid=parameter,cv=5)
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [16]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [17]:
classifier=LogisticRegression(C=1,penalty="l2")

In [18]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [19]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [20]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))


[[10  0]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

1.0


## **RandomizedSearchCV:-**

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html

In [21]:
from sklearn.model_selection import RandomizedSearchCV
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameter)

In [22]:
random_clf.fit(x_train,y_train)

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [23]:
random_clf.best_params_

{'penalty': None, 'C': 10}

logistic regression model with this parameter:-

In [24]:
classifier=LogisticRegression(penalty=None,C=10)

In [25]:
classifier.fit(x_train,y_train)

LogisticRegression(C=10, penalty=None)

In [26]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [27]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[10  0]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

1.0
